version: '3'
services:
    mysql:
        image: "mysql"
        container_name: mysql
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=root
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=database
        ports:
        - "3306:3306"
        expose:
        - 3306
